// Furniture catalog for room customization
import { FurnitureItem } from './types';

export const furnitureCatalog: FurnitureItem[] = [
  // BEDS
  {
    id: 'bed_basic',
    name: 'Basic Bed',
    category: 'bed',
    rarity: 'common',
    price: 0,
    currency: 'cool',
    imageUrl: '/furniture/bed_basic.png',
    dimensions: { width: 2, height: 1 },
    interactable: true,
  },
  {
    id: 'bed_loft',
    name: 'Loft Bed',
    category: 'bed',
    rarity: 'common',
    price: 200,
    currency: 'cool',
    imageUrl: '/furniture/bed_loft.png',
    dimensions: { width: 2, height: 1 },
    interactable: true,
    effects: { stat: 'cool', bonus: 5 },
  },
  {
    id: 'bed_canopy',
    name: 'Canopy Bed',
    category: 'bed',
    rarity: 'rare',
    price: 50,
    currency: 'hallpass',
    imageUrl: '/furniture/bed_canopy.png',
    dimensions: { width: 2.5, height: 1.5 },
    interactable: true,
    effects: { stat: 'social', bonus: 10 },
  },
  {
    id: 'bed_gaming',
    name: 'Gaming Bunk',
    category: 'bed',
    archetype: 'nerd',
    rarity: 'epic',
    price: 100,
    currency: 'hallpass',
    imageUrl: '/furniture/bed_gaming.png',
    dimensions: { width: 2, height: 1 },
    interactable: true,
    effects: { unlocksMinigame: 'esports_arena' },
  },
  {
    id: 'bed_futon',
    name: 'Futon',
    category: 'bed',
    rarity: 'common',
    price: 150,
    currency: 'cool',
    imageUrl: '/furniture/bed_futon.png',
    dimensions: { width: 2, height: 1 },
    interactable: true,
  },
  
  // DESKS
  {
    id: 'desk_basic',
    name: 'Basic Desk',
    category: 'desk',
    rarity: 'common',
    price: 0,
    currency: 'cool',
    imageUrl: '/furniture/desk_basic.png',
    dimensions: { width: 1.5, height: 0.8 },
    interactable: true,
  },
  {
    id: 'desk_gaming',
    name: 'Gaming Setup',
    category: 'desk',
    archetype: 'nerd',
    rarity: 'rare',
    price: 300,
    currency: 'cool',
    imageUrl: '/furniture/desk_gaming.png',
    dimensions: { width: 2, height: 1 },
    interactable: true,
    effects: { stat: 'knowledge', bonus: 15 },
  },
  {
    id: 'desk_art',
    name: 'Art Station',
    category: 'desk',
    archetype: 'artist',
    rarity: 'rare',
    price: 40,
    currency: 'hallpass',
    imageUrl: '/furniture/desk_art.png',
    dimensions: { width: 2, height: 1 },
    interactable: true,
    effects: { stat: 'creative', bonus: 20 },
  },
  {
    id: 'desk_vanity',
    name: 'Vanity',
    category: 'desk',
    archetype: 'popular',
    rarity: 'rare',
    price: 35,
    currency: 'hallpass',
    imageUrl: '/furniture/desk_vanity.png',
    dimensions: { width: 1.5, height: 0.8 },
    interactable: true,
    effects: { stat: 'social', bonus: 15 },
  },
  
  // STORAGE
  {
    id: 'locker_basic',
    name: 'School Locker',
    category: 'storage',
    rarity: 'common',
    price: 100,
    currency: 'cool',
    imageUrl: '/furniture/locker_basic.png',
    dimensions: { width: 0.8, height: 2 },
    interactable: true,
  },
  {
    id: 'bookshelf_wood',
    name: 'Wooden Bookshelf',
    category: 'storage',
    rarity: 'common',
    price: 150,
    currency: 'cool',
    imageUrl: '/furniture/bookshelf_wood.png',
    dimensions: { width: 1, height: 2 },
    interactable: false,
    effects: { stat: 'knowledge', bonus: 5 },
  },
  {
    id: 'wardrobe_modern',
    name: 'Modern Wardrobe',
    category: 'storage',
    rarity: 'rare',
    price: 25,
    currency: 'hallpass',
    imageUrl: '/furniture/wardrobe_modern.png',
    dimensions: { width: 1.5, height: 2 },
    interactable: true,
  },
  
  // CHAIRS
  {
    id: 'chair_desk',
    name: 'Desk Chair',
    category: 'chair',
    rarity: 'common',
    price: 50,
    currency: 'cool',
    imageUrl: '/furniture/chair_desk.png',
    dimensions: { width: 0.8, height: 0.8 },
    interactable: true,
  },
  {
    id: 'chair_gaming',
    name: 'Gaming Chair',
    category: 'chair',
    archetype: 'nerd',
    rarity: 'rare',
    price: 20,
    currency: 'hallpass',
    imageUrl: '/furniture/chair_gaming.png',
    dimensions: { width: 0.8, height: 0.8 },
    interactable: true,
    effects: { stat: 'cool', bonus: 10 },
  },
  {
    id: 'chair_ball',
    name: 'Exercise Ball',
    category: 'chair',
    archetype: 'jock',
    rarity: 'common',
    price: 80,
    currency: 'cool',
    imageUrl: '/furniture/chair_ball.png',
    dimensions: { width: 0.8, height: 0.8 },
    interactable: true,
    effects: { stat: 'athletic', bonus: 5 },
  },
  
  // WALL DECOR
  {
    id: 'poster_band',
    name: 'Band Poster',
    category: 'wall',
    archetype: 'goth',
    rarity: 'common',
    price: 50,
    currency: 'cool',
    imageUrl: '/furniture/poster_band.png',
    dimensions: { width: 0.8, height: 1.2 },
    interactable: false,
  },
  {
    id: 'poster_sports',
    name: 'Sports Poster',
    category: 'wall',
    archetype: 'jock',
    rarity: 'common',
    price: 50,
    currency: 'cool',
    imageUrl: '/furniture/poster_sports.png',
    dimensions: { width: 0.8, height: 1.2 },
    interactable: false,
    effects: { stat: 'athletic', bonus: 5 },
  },
  {
    id: 'poster_art',
    name: 'Art Print',
    category: 'wall',
    archetype: 'artist',
    rarity: 'rare',
    price: 100,
    currency: 'cool',
    imageUrl: '/furniture/poster_art.png',
    dimensions: { width: 1, height: 1.5 },
    interactable: false,
    effects: { stat: 'creative', bonus: 10 },
  },
  {
    id: 'shelf_floating',
    name: 'Floating Shelves',
    category: 'wall',
    rarity: 'common',
    price: 75,
    currency: 'cool',
    imageUrl: '/furniture/shelf_floating.png',
    dimensions: { width: 1.5, height: 0.3 },
    interactable: false,
  },
  {
    id: 'neon_sign_cool',
    name: '"Stay Cool" Neon',
    category: 'wall',
    rarity: 'epic',
    price: 75,
    currency: 'hallpass',
    imageUrl: '/furniture/neon_cool.png',
    dimensions: { width: 1.2, height: 0.5 },
    interactable: true,
    effects: { stat: 'cool', bonus: 15 },
  },
  {
    id: 'tapestry_mandala',
    name: 'Mandala Tapestry',
    category: 'wall',
    archetype: 'artist',
    rarity: 'rare',
    price: 30,
    currency: 'hallpass',
    imageUrl: '/furniture/tapestry_mandala.png',
    dimensions: { width: 2, height: 2 },
    interactable: false,
    effects: { stat: 'creative', bonus: 10 },
  },
  
  // FLOOR DECOR
  {
    id: 'rug_shag',
    name: 'Shag Rug',
    category: 'floor',
    rarity: 'common',
    price: 100,
    currency: 'cool',
    imageUrl: '/furniture/rug_shag.png',
    dimensions: { width: 2, height: 2 },
    interactable: false,
  },
  {
    id: 'plant_succulent',
    name: 'Succulent Collection',
    category: 'decor',
    rarity: 'common',
    price: 40,
    currency: 'cool',
    imageUrl: '/furniture/plant_succulent.png',
    dimensions: { width: 0.5, height: 0.3 },
    interactable: false,
  },
  {
    id: 'trophy_case',
    name: 'Trophy Case',
    category: 'decor',
    archetype: 'jock',
    rarity: 'rare',
    price: 200,
    currency: 'cool',
    imageUrl: '/furniture/trophy_case.png',
    dimensions: { width: 1, height: 1.5 },
    interactable: true,
    effects: { stat: 'athletic', bonus: 10 },
  },
  {
    id: 'skateboard_rack',
    name: 'Skateboard Rack',
    category: 'decor',
    archetype: 'rebel',
    rarity: 'common',
    price: 60,
    currency: 'cool',
    imageUrl: '/furniture/skateboard_rack.png',
    dimensions: { width: 1, height: 1.5 },
    interactable: false,
    effects: { stat: 'cool', bonus: 8 },
  },
  {
    id: 'vinyl_records',
    name: 'Vinyl Collection',
    category: 'decor',
    archetype: 'goth',
    rarity: 'rare',
    price: 150,
    currency: 'cool',
    imageUrl: '/furniture/vinyl_records.png',
    dimensions: { width: 0.8, height: 1 },
    interactable: true,
  },
  {
    id: 'gaming_figurines',
    name: 'Gaming Figurines',
    category: 'decor',
    archetype: 'nerd',
    rarity: 'rare',
    price: 25,
    currency: 'hallpass',
    imageUrl: '/furniture/gaming_figurines.png',
    dimensions: { width: 0.6, height: 0.4 },
    interactable: false,
    effects: { stat: 'cool', bonus: 12 },
  },
  {
    id: 'selfie_ring',
    name: 'Selfie Ring Light',
    category: 'decor',
    archetype: 'popular',
    rarity: 'rare',
    price: 20,
    currency: 'hallpass',
    imageUrl: '/furniture/selfie_ring.png',
    dimensions: { width: 0.5, height: 0.5 },
    interactable: true,
    effects: { stat: 'social', bonus: 10 },
  },
  
  // LIGHTING
  {
    id: 'lamp_desk',
    name: 'Desk Lamp',
    category: 'lighting',
    rarity: 'common',
    price: 30,
    currency: 'cool',
    imageUrl: '/furniture/lamp_desk.png',
    dimensions: { width: 0.4, height: 0.6 },
    interactable: true,
  },
  {
    id: 'led_strips',
    name: 'RGB LED Strips',
    category: 'lighting',
    rarity: 'rare',
    price: 15,
    currency: 'hallpass',
    imageUrl: '/furniture/led_strips.png',
    dimensions: { width: 3, height: 0.1 },
    interactable: true,
  },
  {
    id: 'fairy_lights',
    name: 'Fairy Lights',
    category: 'lighting',
    rarity: 'common',
    price: 25,
    currency: 'cool',
    imageUrl: '/furniture/fairy_lights.png',
    dimensions: { width: 3, height: 0.5 },
    interactable: true,
  },
];

// Utility functions
export function getFurnitureById(id: string): FurnitureItem | undefined {
  return furnitureCatalog.find((item) => item.id === id);
}

export function getFurnitureByCategory(category: string): FurnitureItem[] {
  return furnitureCatalog.filter((item) => item.category === category);
}

export function getFurnitureByArchetype(archetype: string): FurnitureItem[] {
  return furnitureCatalog.filter((item) => item.archetype === archetype || !item.archetype);
}

export function getAffordableFurniture(coolPoints: number, hallPasses: number): FurnitureItem[] {
  return furnitureCatalog.filter(
    (item) =>
      (item.currency === 'cool' && item.price <= coolPoints) ||
      (item.currency === 'hallpass' && item.price <= hallPasses)
  );
}
